### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Zelurium** [cosmicnebula200/FunBlockOneBlock#11]
/oneblock delete "server closed" 

Error: Call to a member function getName() on null
File: plugins/FunBlockOneBlock_dev-60.phar/src/cosmicnebula200/FunBlockOneBlock/oneblock/OneBlockManager
Line: 113
Type: Error

**Comment by cosmicnebula200** [comment]
> /oneblock delete "server closed"
> 
> Error: Call to a member function getName() on null File: plugins/FunBlockOneBlock_dev-60.phar/src/cosmicnebula200/FunBlockOneBlock/oneblock/OneBlockManager Line: 113 Type: Error

Hey Zelurium,
I have fixed this error, if you use the latest build from poggit CLI this should not be occuring anymore 👍
