### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by EvilDevil1175** [cosmicnebula200/FunBlockOneBlock#4]
compatible with api 3.0.0 pls

**Comment by cosmicnebula200** [comment]
> compatible with api 3.0.0 pls

Currently I have stopped working on pm3.

**Comment by EvilDevil1175** [comment]
pls make a api 3.0.0

**Comment by DretooFuni** [comment]
> > compatible with api 3.0.0 pls
> 
> Currently I have stopped working on pm3

No.
